apiVersion: apps/v1
kind: Deployment
metadata:
  name: drachtio
  namespace: voip-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drachtio
  template:
    metadata:
      labels:
        app: drachtio
    spec:
      containers:
      - name: drachtio-server
        image: drachtio/drachtio-server:latest
        ports:
          - containerPort: 9022
            protocol: TCP
          - containerPort: 5060
            protocol: UDP
        env:
          - name: DRACHTIO_SECRET
            value: "cymru"   # set same secret in app
      - name: node-app
        image: my-node-app:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: DRACHTIO_HOST
            value: "drachtio.voip-test.svc.cluster.local"
          - name: DRACHTIO_PORT
            value: "9022"
          - name: DRACHTIO_SECRET
            value: "cymru"
          - name: RTPENGINE_HOST
            value: "rtpengine.voip-test.svc.cluster.local"
          - name: RTPENGINE_PORT
            value: "22222"
        ports:
          - containerPort: 3000
            protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
