apiVersion: v1
kind: Service
metadata:
  name: drachtio
  namespace: voip-test
spec:
  type: ClusterIP
  selector:
    app: drachtio
  ports:
    - name: sip
      port: 5060
      targetPort: 5060
      protocol: UDP
    - name: api
      port: 9022
      targetPort: 9022
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: drachtio-external
  namespace: voip-test
spec:
  type: LoadBalancer
  selector:
    app: drachtio
  ports:
    - name: sip
      port: 5060       # Port Zoiper will use externally
      targetPort: 5060 # Matches Drachtio container
      protocol: UDP
    - name: api
      port: 9022
      targetPort: 9022
      protocol: TCP
