apiVersion: apps/v1
kind: Deployment
metadata:
  name: drachtio
  namespace: voip-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drachtio
  template:
    metadata:
      labels:
        app: drachtio
    spec:
      containers:
        - name: drachtio
          image: drachtio/drachtio-server:0.9.3
          ports:
            - containerPort: 5060
              protocol: UDP
            - containerPort: 9022
              protocol: TCP
          volumeMounts:
            - name: drachtio-config
              mountPath: /etc/drachtio.conf.xml
              subPath: drachtio.conf.xml
      volumes:
        - name: drachtio-config
          configMap:
            name: drachtio-config
