apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeswitch
  namespace: voip-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freeswitch
  template:
    metadata:
      labels:
        app: freeswitch
    spec:
      containers:
      - name: freeswitch
        image: customswitch-app:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
          - name: sip-udp
            containerPort: 5060
            protocol: UDP
          - name: sip-tcp
            containerPort: 5061
            protocol: TCP
          - name: esl
            containerPort: 8021
            protocol: TCP
