apiVersion: v1
kind: Service
metadata:
  name: freeswitch
  namespace: voip-test
spec:
  type: ClusterIP
  selector:
    app: freeswitch
  ports:
    - name: sip
      port: 5060
      targetPort: 5060
      protocol: UDP
    - name: sip-tls
      port: 5061
      targetPort: 5061
      protocol: TCP
    - name: esl
      port: 8021
      targetPort: 8021
      protocol: TCP
