apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtpengine
  namespace: voip-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtpengine
  template:
    metadata:
      labels:
        app: rtpengine
    spec:
      containers:
        - name: rtpengine
          image: jambonz/rtpengine:latest # Replace with your image
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: ng
              containerPort: 22222
              protocol: TCP
            - name: rtp-proxy
              containerPort: 12222
              protocol: UDP
          volumeMounts:
            - name: rtpengine-config
              mountPath: /etc/rtpengine/rtpengine.conf
              subPath: rtpengine.conf
      volumes:
        - name: rtpengine-config
          configMap:
            name: rtpengine-config
